- src/tutorial/01-Setup/00.md
- src/tutorial/01-Setup/a.md
- src/tutorial/01-Setup/b.md
- src/tutorial/01-Setup/c.md
- src/tutorial/01-Setup/e.md
This is intended to clear up confusion about how
Activator relates to sbt, and whether people need
both or what. The Activator install page explains
how Activator is different from sbt and how it's
the same. This should avoid a few FAQs, hopefully.
> Add Activator as an installation option

- src/reference/02-DetailTopics/05-Plugins-and-Best-Practices/04-Travis-CI-with-sbt.md
Originally reported by @xuwei-k 
The actual boot path is like `~/.sbt/boot/scala-2.10.4/org.scala-sbt/sbt/0.13.7`.
/review @jsuereth, @xuwei-k
> Fix Travis instruction on ~/.sbt/boot

- src/reference/01-General-Info/02-Community-Plugins.md
The tabular test reporter produces test results
well suited for further processing and analysis.
> Adding link to test reporter plugin

- src/reference/01-General-Info/02-Community-Plugins.md
Add sbt-play-scalajs to community plugins under the `Web and frontend development plugins` section.
> Add sbt-play-scalajs to community plugins.

- src/reference/01-General-Info/02-Community-Plugins.md
I'd like to add the sbt-codedeploy. Before this gets merged could someone make sure that the plugin adheres to the community standards. I think it does, but this is the first plugin I've contributed to SBT, so I just want to make sure everything's in the right place for this initial release.
> Add sbt-codedeploy to community plugins

- src/reference/02-DetailTopics/01-Using-sbt/07-Incremental-Recompilation.md
This PR integrates my notes on incremental compilation that live here: https://github.com/gkossakowski/sbt/wiki/Incremental-compiler-notes
After copy&pasting information about implementation details of inc and name hashing I went on to update it with latest developments. My notes were written before name hashing got merged into sbt.
The overall shape of the `07-Incremental-Recompilation.md` is slightly better with this PR than without it. I recognize it's not ideal but I've ran out of time to improve it further.
> Integrate notes on incremental compilation

- src/tutorial/01-Setup/d.md
- src/tutorial/es/01-Setup/d.md
- src/tutorial/ja/01-Setup/d.md
- src/tutorial/zh-cn/01-Setup/d.md
Launching the script from application like emacs doesn't work if there's no shebang in the script.
> Add shebang for manual unix launch script

- src/reference/01-General-Info/02-Community-Plugins.md
Please add a link to new my sbt plugin that checks code style of Java projects in a handy way: https://github.com/xerial/sbt-jcheckstyle
> Add link to sbt-jcheckstyle plugin

- src/reference/02-DetailTopics/04-Tasks-and-Commands/05-Build-State.md
Update the 'Running tasks' example to use `Project.runTask` since
`Project.evaluateTask` was deprecated in SBT 0.11.1.
Note: I tested that the example compiles, but didn't actually run it.
> Use runTask instead of deprecated evaluateTask

- src/reference/01-General-Info/02-Community-Plugins.md
sbt-api-mappings is a Sbt plugin that fills apiMappings for common Scala libraries
> Add sbt-api-mappings

- src/reference/01-General-Info/02-Community-Plugins.md
[sbt-frege](https://github.com/earldouglas/sbt-frege) is an sbt plugin for building [Frege](https://github.com/frege/frege) code, and was recently added to the sbt community repository.  This patch lists it along with the other code generation plugins.
> Add link to sbt-frege plugin

- src/reference/01-General-Info/02-Community-Plugins.md
- src/reference/01-General-Info/90-Changes/90-Older-Changes.md
- src/reference/05-Faq/00.md
- src/tutorial/10-Using-Plugins.md
- src/tutorial/ja/10-Using-Plugins.md
- src/tutorial/zh-cn/10-Using-Plugins.md
[JamesEarlDouglas/xsbt-web-plugin](https://github.com/JamesEarlDouglas/xsbt-web-plugin) is just a redirect to [earldouglas/xsbt-web-plugin](https://github.com/earldouglas/xsbt-web-plugin).  This patch skips the extra jump.
> Update links to xsbt-web-plugin

- src/reference/01-General-Info/02-Community-Plugins.md
I know people are using this documentation to find plugins for SBT, and two plugins that I think are really worth noting haven't made it in:  Brian McKenna's Wartremover, and Rob Norris's Tut.
I got out-of-memory errors when trying to build the docs, so I apologize for not rigorously testing that these changes are well-formed.  But it's just three lines, so hopefully it's easy enough to check upon inspection.
I tried to format the lines similarly to surrounding lines, though there's some inconsistency across the file.
> reference Tut and WartRemover plugins

- src/reference/04-Howto/08-Howto-Package.md
The previous code snippet did not compile. We have to specify the file
that needs to be loaded.
> Fix documentation about how to load manifst from a file

- src/reference/02-DetailTopics/03-Dependency-Management/04-Proxy-Repositories.md
- src/reference/03-Developers-Guide/09-Launcher/03-Launcher-Configuration.md
- Correct URL to launcher configuration.
- Correct path to local maven repo. I believe this is correct based on the behavior I see.
> Launcher related typos

- src/tutorial/10-Using-Plugins.md
Sorry, I couldn't help it but either "need to *be* explicitly enabled" or  "need to explicitly *be* enabled" sounds better in my head.
> Minor grammar fix

- src/reference/01-General-Info/02-Community-Plugins.md
Scavro is being migrated off of the oysterbooks github repo and off the com.oysterbooks group.
> Updating location of Scavro repo

- src/reference/04-Howto/13-Howto-Custom-Tasks.md
derived from: http://stackoverflow.com/questions/9856204/sbt-skip-tests-in-subproject-unless-running-from-within-that-project
> Snippet showing how to invoke specific tasks

- src/reference/02-DetailTopics/05-Plugins-and-Best-Practices/04-Travis-CI-with-sbt.md
`find | xargs rm` is dangerous (you need `find -print0 | xargs -0 rm`) and slow.
See https://www.gnu.org/software/findutils/manual/html_node/find_html/Deleting-Files.html for a discussion
> Use after_script and "-delete" to clean up files

- src/nanoc/content/download.html
Receive keys via fingerprint (please verify it). Short IDs are only 32-bit can thus be easily forged.
> Download section: use key fingerprint

- src/reference/02-DetailTopics/05-Plugins-and-Best-Practices/02-Plugins.md
Trying to fix the uncompilable example, replacing `Command` with `Task` according to the best practice.
> Fix #221 Replace `Command` with `Task` in HelloPlugin3 example

- src/reference/90-Developers-Guide/09-Launcher/03-Launcher-Configuration.md
I've copied an example from http://www.scala-sbt.org/0.13.5/docs/Launcher/Configuration.html.
> Added missing launcher configuration example

- src/reference/01-General-Info/02-Community-Plugins.md
Add Courier's sbt plugin to the list of code generator plugins on the community plugins page.
> Add courier to community plugins list

- src/nanoc/content/arc.js
navigator.appVersion only returns "5.0 (X11)" on Firefox Ubuntu so people have to look for sbt Debian packages in the documentation. This navigator.userAgent seems to be more reliable on all platforms.
> Use navigator.userAgent for more reliable os detection on Linux Firefox

- src/reference/04-Howto/09-Howto-Running-Commands.md
Fix an example, changing single quotes to double quotes (fixes #263).
> Fix error in example

- src/reference/ja/00-Getting-Started/08-Library-Dependencies.md
http://www.scala-sbt.org/0.13/docs/ja/Library-Dependencies.html
> fix specs2 url link. remove unused specs link

- src/reference/01-General-Info/02-Community-Plugins.md
I'd like to add [sbt-aws-fun](https://github.com/TailrecIO/sbt-aws-fun) plugin to the community plugins page.
Thank you!
> Add sbt-aws-fun to the community plugins page

- src/reference/02-DetailTopics/03-Dependency-Management/08-Cached-Resolution.md
> Fix typo (libary -> library)

- src/reference/01-General-Info/02-Community-Plugins.md
sbt-play-scalajs has been renamed to sbt-web-scalajs because it has no Play dependency, it only depends on sbt-web and Scala.js.
> Add sbt-web-scalajs to 02-Community-Plugins.md.

- src/reference/02-DetailTopics/04-Tasks-and-Commands/02-Input-Tasks.md
Remove `,` before `:`
To make `:` consistent.
> remove ',' before ':'

- src/reference/00-Getting-Started/01-Setup/c.md
You can verify the long key ID is the only one corresponding to the short key ID (at present) on the keyserver using the following command:
gpg --dry-run --keyid-format long --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 642AC823
Using short key IDs is not safe, and there are already real-world attacks out there against this - see https://lkml.org/lkml/2016/8/15/445.
> Use long key ID instead of short one

- src/reference/01-General-Info/05-Using-Sonatype.md
Clicking on the sbt-pgp link on
http://www.scala-sbt.org/1.0/docs/Using-Sonatype.html
produce a 404 not found, because Google Analytics is appending a query string:
http://www.scala-sbt.org/sbt-pgp?_ga=1.200222766.1442054452.1475176157
If it's possible for GitHub sites to ignore query strings for files, that would probably also fix this.  Interestingly, though, making it a directory by adding a trailing-slash seems to work regardless of the query string.  e.g.  http://www.scala-sbt.org/sbt-pgp/?_ga=1.200222766.1442054452.1475176157
> Add trailing-slash to sbt-pgp link to fix GA defect

- .travis.yml
- README.md
It's not clear what version of Ruby you need to build the nanoc docs, but I noticed that if you update the minor version, you only need Ruby 2.1.  I've updated the documentation and the Travis yml file.
I ran the `makeSite` command with nanoc 4.0.0 and Ruby 2.2.5, then copied the `target` file, then built it with 2.1.10 and nanoc 4.0.2.  Comparing the target file before and after with `diff`, I noticed there were very few differences:  Just the `.manifest` files and the PDFs.
> Mention Ruby 2.1 for nanoc

- src/reference/02-DetailTopics/05-Plugins-and-Best-Practices/06-sbt-new-and-Templates.md
As scala-seed will be the "official" minimal project template, I think it makes sense to use it instead of `eed3si9n/hello.g8`.
Also, `sbt new` with `scala-seed` doesn't ask for the Scala version, hence updating example output block.
> Use scala-seed as the example sbt new template

- README.md
Explicitly document the Java 7 dependency in the README?
> Require Java 7 to avoid #143 defect

- src/reference/90-Developers-Guide/00.md
- src/reference/90-Developers-Guide/01-Modularization/00.md
- src/reference/90-Developers-Guide/01-Modularization/01-Module-Summary.md
- src/reference/90-Developers-Guide/02-Coding-Guideline/00.md
- src/reference/90-Developers-Guide/06-Datatype/00.md
- src/reference/90-Developers-Guide/08-Compiler-Interface/00.md
- src/reference/90-Developers-Guide/08-Compiler-Interface/01-Version-Specific-Sources.md
- src/reference/90-Developers-Guide/09-Launcher/01-Launcher-Getting-Started.md
- src/reference/90-Developers-Guide/09-Launcher/02-Launcher-Architecture.md
- src/reference/90-Developers-Guide/09-Launcher/03-Launcher-Configuration.md
- src/reference/90-Developers-Guide/10-DevGuide-Notes/01-Core-Principles.md
- src/reference/90-Developers-Guide/10-DevGuide-Notes/02-Settings-Core.md
- src/reference/90-Developers-Guide/10-DevGuide-Notes/03-Setting-Initialization.md
I've rebased #230 against master and resolved the conflicts.  It appears I have all the fixes, by studying the output of the following:
```
$ git diff -U0 996fb7c..ches/dev-guide-typos    > dev-guide-typos.patch~
$ git diff -U0 master..ashawley/dev-guide-typos > dev-guide-typos.patch
$ diff -u dev-guide-typos.patch~ dev-guide-typos.patch
```
To be honest I actually run `sed -i -e 's/ @@ .*/ @@/'` on the patches to remove chunk headers.
Later this week, I'll try to incorporate the outstanding comments in #230 and then autosquash.
> Second pass at developer guide typos

- src/reference/90-Developers-Guide/02-Coding-Guideline/00.md
As discussed in https://github.com/sbt/sbt/issues/2389
The docs currently claim we want to cross-build against scala 2.10. Is that still accurate?
> sbt 1.0 will target scala 2.12

- src/reference/02-DetailTopics/02-Configuration/09-Macro-Projects.md
To publishing macro bundled project, dependency to macrosub should be changed.
For more detail, see http://stackoverflow.com/a/31874801/4006322 .
> Fix code for macro bundled project publishing

- src/reference/05-Faq/00.md
- src/reference/90-Developers-Guide/09-Launcher/01-Launcher-Getting-Started.md
- src/reference/90-Developers-Guide/10-DevGuide-Notes/05-Command-Line-Applications.md
Fixes #319
For the most part the docs avoid the "sbt X" (e.g "sbt compile") form.
These are just a few trailing cases I found.
To seek and destroy them I used `git grep`. First I found I can exclude
irrelevant paths and files by appending:
-- ':/' ':/!/src/reference/ja/' ':/!/src/reference/es/' ':/!/src/reference/zh-cn/' ':/!*.js' ':/!*.css'
(from http://stackoverflow.com/a/30084612/463761)
So I ran the following searches with that appended:
git grep '[^\.]sbt '
git grep '`[^`]*sbt '
git grep '  sbt '
git grep '	sbt'
(that last one is a literal tab, i.e the literal form of \t)
> Tweaks to favour use of the shell

- src/reference/02-DetailTopics/05-Plugins-and-Best-Practices/04-Travis-CI-with-sbt.md
+ Drop the "experimental" and generalise it to caching
+ Change to caching all of ~/.sbt, which means launchers in
~/.sbt/launchers are cached
+ Drop the "tricks" in the before_cache instruction
+ Cleanup ivydata-*.properties in ~/.ivy2/cache
+ Print out things that are deleted, useful for debugging
> Tweak Travis CI caching setup

- src/reference/01-General-Info/02-Community-Plugins.md
Adding link to new plugin that provides a `sbt-assembly` MergeStrategy
for `log4j2` plugin cache files (`Log4j2Plugins.dat`).
> Add sbt-assembly-log4j2 to community plugins list

- src/reference/01-General-Info/02-Community-Plugins.md
Added sbt-scripted-scalatest (a plugin to use ScalaTest with scripted-plugin to test SBT plugins)
> Add sbt-scripted-scalatest to community plugins list

- src/reference/01-General-Info/02-Community-Plugins.md
https://github.com/orfjackal/idea-sbt-plugin is deprecated since most of its functionality is covered directly by IntelliJ-Scala and it is outdated relative to the IntelliJ platform API.
> add sbt-dash, remove idea-sbt-plugin

- README.md
- src/reference/02-DetailTopics/04-Tasks-and-Commands/02-Input-Tasks.md
The import is needed for the first basic example to work, whether in a plugin or directly in the build.sbt. The README also had a typo.
> Add missing import for InputTask example and fix typo in README

- project/Docs.scala
Do you need the output from generating redirects for your workflow or could they be silenced?  If you need a record of these, maybe it's possible to parameterize the `logLevel` to `Level.debug` for Travis or when you deploy.
> Use debug log for redirect gen

- src/reference/01-General-Info/02-Community-Plugins.md
Adds a reference to a new plugin I'm developing, that integrates with the GitLab API's. Currently it allows a user to control gitlab-ci pipelines.
> Adding reference to sbt-gitlab plugin

- src/reference/00-Getting-Started/07B-Appending-Values.md
Link to scopes in [Appending-Values](http://www.scala-sbt.org/0.13/docs/Appending-Values.html#When+settings+are+undefined) chapter is rendered as `[scope][Scopes]`, this commit fixes that.
> Add missing reference to Appending-Values chapter

- src/reference/01-General-Info/02-Community-Plugins.md
sbt-updates 0.3.1 is cross-built for sbt 1.0.0-M5 and 1.0.0-M6
> Add sbt-updates to the list of sbt 1.0.0 plugins

- src/reference/01-General-Info/02-Community-Plugins.md
#366 linked to Travis CI by mistake instead of GitHub.
> Fixed sbt-updates plugin link

- src/reference/02-DetailTopics/01-Using-sbt/03-Cross-Build.md
Hey,
I was searching for the `++` information and missed it while skimming the documentation and finally found it in a third party website. It's only when I started writting the PR to add it that I realized it was already present. 
I still made this pr because I belive I'm probably not the first one to miss it.
> Move crosscompile ++ doc

- .travis.yml
- Use apt addons packages syntax
- Use new apt sources syntax
Currently, the apt sources syntax requires a `gpg.key` over HTTP.
> Use Travis apt sources

- src/reference/02-DetailTopics/02-Configuration/14-Testing.md
The `testForkedParallel` feature is almost 4 years old, and in the time that it has existed, there has never been a confirmed bug report against it. It shouldn't be considered experimental anymore.
> Remove experimental warning from testForkedParallel
