sbt/website

- src/reference/01-General-Info/02-Community-Plugins.md
sbt-phantomjs is an automated installer and configurator for PhantomJS
> Add sbt-phantomjs to the community plugin list

- src/reference/01-General-Info/02-Community-Plugins.md
:point_right: https://github.com/tototoshi/sbt-build-files-watcher
> Added sbt-build-files-watcher

- src/reference/02-DetailTopics/01-Using-sbt/06-Scripts.md
Update sbt 0.12 => 0.13 when using cs install sbt
> Update sbt 0.12 => 0.13 when using cs install sbt

- src/reference/02-DetailTopics/05-Plugins-and-Best-Practices/04-Travis-CI-with-sbt.md
- src/reference/template.properties
> Travis integration

- src/reference/03-Developers-Guide/00.md
> Add notes about modularization of launcher.

- src/reference/02-DetailTopics/01-Using-sbt/07-Incremental-Recompilation.md
These are small fixes. Bigger changes that merge with my notes on inc are coming.
> Inc documentation improvements

- src/reference/01-General-Info/02-Community-Plugins.md
https://github.com/scalatra/scalatra-sbt
> Add scalatra-sbt to community plugins

- src/reference/02-DetailTopics/03-Dependency-Management/05-Publishing.md
Per sbt/sbt Gitter comments on June 2, 2015.
> Made artifact repository examples fictitious

- src/nanoc/content/community.md
Not sure how to word it, so feedback very welcome.
> Add new sbt-dev gitter channel to community page.

- src/reference/01-General-Info/02-Community-Plugins.md
Simple plugin for running solr from sbt.
> Solr-plugin

- src/reference/02-DetailTopics/01-Using-sbt/06-Scripts.md
> Remove dead server references.

- src/reference/03-Developers-Guide/02-Coding-Guideline/00.md
Draft guideline on sbt 1.0 refactoring.
/review @jsuereth, @dwijnand, @Duhemm
> coding guideline

- src/reference/01-General-Info/02-Community-Plugins.md
Adding scavro to community plugins
> Adding scavro to community plugins

- src/reference/02-DetailTopics/02-Configuration/13-Running-Project-Code.md
this is touched on in a few other places in the doc, but
it seemed strange to me that it wasn't covered here
> add a bit of doc on runMain

- src/nanoc/content/download.html
- src/nanoc/nanoc.yaml
> Fix windows build for 0.13.9. Fixes sbt/sbt#2181

- src/reference/01-General-Info/02-Community-Plugins.md
https://github.com/localytics/sbt-dynamodb
> Add sbt-dynamodb to the sbt plugins community page

- src/reference/02-DetailTopics/02-Configuration/05-Global-Settings.md
See https://github.com/sbt/sbt/issues/2364
> Document the need to have fully qualified names for global plugin settings

- src/reference/layouts/header.md
> Fixes #117 by automatically scrolling 120px on hashchange

- src/reference/01-General-Info/90-Changes/48-sbt-0.13-Tech-Previews.md
> Tweaks to 0.13.10 release notes

- src/reference/02-DetailTopics/01-Using-sbt/06-Scripts.md
Migrated from sbt/sbt.github.com#32
> Fix link to sbt-extras

- src/reference/01-General-Info/02-Community-Plugins.md
Adding the SBT plugin 'sbt-pillar' to the Community Plugins list
> Add 'sbt-pillar' plugin to community plugin list

- src/nanoc/content/documentation.md
https://github.com/sbt/website/issues/129#issuecomment-210436532
> delete "Not the latest"

- src/reference/01-General-Info/02-Community-Plugins.md
Add the Naptime API system's sbt plugin to the community plugins page.
> Add Naptime to community plugins

- src/reference/00-Getting-Started/11-Custom-Settings.md
> Typo in 11-Custom-Settings.md

- src/reference/02-DetailTopics/03-Dependency-Management/03-Library-Management.md
- src/reference/06-Name-Index.md
I found excludeDependencies very useful, but did not find it in the documentation.
Cheers,
Enno.
> Added section about excludeDependencies in 03-Library-Management

- src/reference/01-General-Info/02-Community-Plugins.md
Added sbt-dependency-check to community plugins
> Added sbt-dependency-check to community plugins

- src/reference/02-DetailTopics/04-Tasks-and-Commands/04-Parsing-Input.md
`flatMap` has been very useful for me, and the documentation doesn't talk about it.
> Document flatMap

- src/reference/01-General-Info/02-Community-Plugins.md
sbt-hocon (operations on HOCON data against reference configuration aggregated from project dependencies)
> sbt-hocon added

- src/reference/01-General-Info/02-Community-Plugins.md
SBT interface to DSL Platform.
> DSL Platform sbt plugin.

- src/reference/01-General-Info/02-Community-Plugins.md
- maybe start a literate programming (sub)section including tut, literator-plugin and sbt-scaliterate?
- would this be worth?
> adds scaliterate plugin to documentation section

- src/reference/02-DetailTopics/05-Plugins-and-Best-Practices/02-Plugins.md
> fix typos, minor cleanup

- src/reference/02-DetailTopics/04-Tasks-and-Commands/02-Input-Tasks.md
comments indention should be the same as surrounding code
> Update comments indention of 02-Input-Tasks.md

- src/reference/02-DetailTopics/01-Using-sbt/03-Cross-Build.md
> Update 03-Cross-Build.md. Fix misprint.

- src/nanoc/nanoc.yaml
- src/reference/template.properties
Ignoring sbtVersionForScalaDoc because of sbt/sbt#2812
> Bump sbt version in website

- src/reference/02-DetailTopics/05-Plugins-and-Best-Practices/06-sbt-new-and-Templates.md
> sbt new and Templates

- build.sbt
- src/nanoc/content/community.md
- src/reference/01-General-Info/02-Community-Plugins.md
- src/reference/02-DetailTopics/03-Dependency-Management/08-Cached-Resolution.md
- src/reference/02-DetailTopics/05-Plugins-and-Best-Practices/04-Travis-CI-with-sbt.md
- src/reference/02-DetailTopics/05-Plugins-and-Best-Practices/06-sbt-new-and-Templates.md
> Github -> GitHub

- src/reference/02-DetailTopics/03-Dependency-Management/08-Cached-Resolution.md
> Typo and grammar

- src/reference/04-Howto/06-Howto-Logging.md
@eed3si9n suggested this in #315.
> Provide a link to Logger's API docs.

- src/reference/02-DetailTopics/01-Using-sbt/03-Cross-Build.md
> Document CrossVersion.patch

- src/reference/01-General-Info/05-Using-Sonatype.md
> Fix markup on Using Sonatype

- src/reference/01-General-Info/02-Community-Plugins.md
Standardizing formatting to `plugin-name (description): <url>`, as mentioned in #343
> Standardized formatting

- src/reference/01-General-Info/90-Changes/45-Migrating-from-sbt-0.12.x.md
Adds migration notes on `sourceGenerators` and `Build` trait.
> More migration notes

- .travis.yml
- Upgrade to Ubuntu 14.04 trusty
- Drop texlive ppa repo
- Don't bother installing ruby-dev with apt
- Drop JVM memory options
> Fix travis build file

- src/reference/01-General-Info/05-Using-Sonatype.md
Another follow-up to #334 
I'm happy to squash my commits in to one.  I've also deferred line-wrapping for review purposes.
> Using Sonatype edits

- src/reference/00-Getting-Started/07A-Scopes.md
> Fix typo in 07A-Scopes.md

- src/reference/01-General-Info/02-Community-Plugins.md
more info on repo: https://github.com/cuzfrog/sbt-tmpfs
> Add plugin sbt tmpfs

- src/reference/04-Howto/03-Howto-Generating-Files.md
Should solve https://github.com/sbt/sbt/issues/1832
> Added comment about running `run` or `package` for resources
